name: prescripcare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  firebase_core: 3.3.0
  firebase_analytics: 11.2.1
  firebase_auth: 5.1.4
  cloud_firestore: 5.2.1
  google_sign_in: 6.2.1
  flutter_screenutil: 5.9.3
  fluttertoast: 8.2.8
  dots_indicator: 3.0.0
  carousel_slider: 5.0.0
  provider: 6.1.2
  image_picker: 1.0.1
  font_awesome_flutter: 10.7.0
  url_launcher: 6.3.1
  firebase_storage: 12.1.3
  cached_network_image: ^3.4.0
  file_picker: 8.0.7
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  fl_chart: ^0.69.0
  flutter_local_notifications: ^18.0.1
  intl: ^0.20.0
  timezone: ^0.10.0
  path_provider: ^2.1.5
  audioplayers: ^6.1.0
  permission_handler: ^11.3.1
  flutter_ringtone_player: ^4.0.0+3
  alarm: ^4.1.1
  flutter_launcher_icons: ^0.14.3
  firebase_messaging: ^15.0.4
  flutter_sound: ^9.1.5
  responsive_framework: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/config/healthcare-irau-6367db0fa19e.json
    - assets/google_logo.png
    - assets/cover.png
    - assets/g.jpg
    - assets/ring.mp3



  # Add assets here

